### ISSUE TITLE
Doesn't work if scheme name contains space

### ISSUE THREAD

**Issue by tadija** [bitrise-tools/codesigndoc#27] opened 2016-11-29 15:38 UTC
Here's output from my terminal:

```
$ bash -l -c "$(curl -sfL https://raw.githubusercontent.com/bitrise-tools/codesigndoc/master/_scripts/install_wrap-xcode.sh) --scheme=Lead Radar Test"
 => Creating a temporary directory for codesigndoc ...
 => Downloading version: 0.9.16
 => Downloading codesigndoc from (https://github.com/bitrise-tools/codesigndoc/releases/download/0.9.16/codesigndoc-Darwin-x86_64) to (/var/folders/x1/_2ctrjwd67x60st1lpybwpmr0000gn/T/codesigndoc.OaFGuRaN/codesigndoc) ...
######################################################################## 100.0%
 => Making it executable ...
 => codesigndoc version: 0.9.16
 => Running codesigndoc scan ...


Please drag-and-drop your Xcode Project (.xcodeproj)
   or Workspace (.xcworkspace) file, the one you usually open in Xcode,
   then hit Enter.

  (Note: if you have a Workspace file you should most likely use that) : /Users/tadija/Documents/Temp/leadradar/leadradar.xcworkspace 


INFO[16:33:32] 🔦  Running an Xcode Archive, to get all the required code signing settings... 
INFO[16:33:32] $ xcodebuild "-workspace" "/Users/tadija/Documents/Temp/leadradar/leadradar.xcworkspace" "-scheme" "Lead" "clean" "archive" 
Running and analyzing log ....

INFO[16:33:33]   💡  Saving xcodebuild output into file: /Users/tadija/Documents/Temp/leadradar/codesigndoc_exports/xcodebuild-output.log 
INFO[16:33:33] Please check the logfile (/Users/tadija/Documents/Temp/leadradar/codesigndoc_exports/xcodebuild-output.log) to see what caused the error 
INFO[16:33:33] and make sure that you can Archive this project from Xcode! 

INFO[16:33:33] Open the project: /Users/tadija/Documents/Temp/leadradar/leadradar.xcworkspace 
INFO[16:33:33] and Archive, using the Scheme: Lead          


------------------------------
First of all please make sure that you can Archive your app from Xcode.
codesigndoc only works if you can archive your app from Xcode.
If you can, and you get a valid IPA file if you export from Xcode,
please create an issue on GitHub at: https://github.com/bitrise-tools/codesigndoc/issues
with as many details & logs as you can share!
------------------------------

Error: Failed to run Xcode Archive: Failed to Archive, error: Failed to run xcodebuild command, error: exit status 65
```

You'll notice that on the first line scheme name is full ("Lead Radar Test"), but later when xcodebuild is called wrong scheme name is used ("Lead").

Log file says the same:

```
xcodebuild: error: The workspace named "leadradar" does not contain a scheme named "Lead". The "-list" option can be used to find the names of the schemes in the workspace.
```

**Comment by viktorbenei** [comment] 2016-11-29 15:48
Thanks for reporting @tadija !

Duplicate of https://github.com/bitrise-tools/codesigndoc/issues/25 - please see the other issue for a solution, and sorry for the inconvenience.

**Closed by viktorbenei** 2016-11-29 15:48 UTC
