### ISSUE TITLE
Failed to export identities

### ISSUE THREAD

**Issue by hcentelles** [bitrise-tools/codesigndoc#37] opened 2017-03-27 18:14 UTC
It export the provisioning profiles only, then when searching for Identity it fails. I'm able to archive and export successfully the project from XCode.

Here is the edited output: [codesigndoc_output.txt](https://github.com/bitrise-tools/codesigndoc/files/873365/codesigndoc_output.txt)

The Xcode output log ends with ```** ARCHIVE SUCCEEDED **```

**Comment by viktorbenei** [comment] 2017-03-28 09:02
The error in the log `Error: Failed to export identities, error: Failed to export, error: Failed to find Identity, error: FindIdentity: failed to get 'labl' property: getCFDictValueCFStringRef: value is not a string` means that you have an item in your Keychain which doesn't have the proper `labl` property. 

Not sure why that might be, I never saw this before. If you have the time, please download the latest binary of `codesigndoc` from the releases page here on GitHub, `chmod +x codesigndoc` it so that you can run it, then: `./codesigndoc -l=debug scan xcode`

This will start codesigndoc in debug mode, where it'll print all the identities it finds. You should see in the log which item causes the issue, or send that log to us so that we can inspect it.

A workaround, other than identifying the item which causes the issue and removing it, is to transfer your signing files to another Mac and run `codesigndoc` there. It's most likely some kind of ancient signing key in your Keychain what causes this issue, but without the `-l=debug` log it's hard to say.

**Comment by viktorbenei** [comment] 2017-07-27 10:07
Closing as we didn't receive a response and there's not enough info here without the `-l=debug` run log; we could not reproduce this issue.

If anyone would have this issue feel free to comment and we'll reopen it, but we'll need the `-l=debug` run log.

**Closed by viktorbenei** 2017-07-27 10:07 UTC
Labels: bug, help wanted, question
