### ISSUE TITLE
CompileSwift normal armv7 output log error

### ISSUE THREAD

**Issue by HannahCarney** [bitrise-tools/codesigndoc#78] opened 2018-05-16 14:18 UTC
Dropping in my iOS Workspace into the command line prompt fails with this in the logs:

Project builds and archieves fine. Using swift 3.3 (have to because of un-updated 3rd party library) and xcode 9.2 (have to because 9.3 won't allow swift 3.3).

running 

`xcodebuild -version `

yields this result: 
Xcode 9.2
Build version 9C40b

The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by daviskoh** [comment] 2018-05-16 23:39
seeing this issue as well

**Comment by godrei** [comment] 2018-05-17 08:40
Hi @HannahCarney ,
thanks for the report! We will have a look at this issue ASAP!

**Comment by daviskoh** [comment] 2018-05-22 04:47
Is this a stale issue?

**Comment by trapacska** [comment] 2018-05-23 09:37
Hey @daviskoh !

It is already in our issue tracker marked with this Github issue, so we will notify you as soon as the issue is fixed. 🚀

**Comment by godrei** [comment] 2018-05-28 09:38
Hi @HannahCarney ,

could you please attach the whole codesigndoc's terminal log and the generated raw-xcodebuild-output-log?

If they contains sensitive informations please write us on bitrise.io on-site chate.

**Comment by godrei** [comment] 2018-06-07 14:00
Closing as we did not receive a reply - @daviskoh please let us know if we can help with anything and we'll reopen this issue!

**Closed by godrei** 2018-06-07 14:00 UTC

**Comment by viktorbenei** [comment] 2018-06-08 16:39
Conversation locked for tracking purposes - please create a new one or contact us via the onsite chat on bitrise.io with the logs so that we can help as quickly as possible! :)
