### ISSUE TITLE
No profile matching

### ISSUE THREAD

**Issue by sketchydroide** [bitrise-tools/codesigndoc#23] opened 2016-11-01 18:32 UTC
I keep getting this error when I try to use the command to get teh provision profiles.

Check dependencies
No profile matching 'XC Ad Hoc: com.laundrapp.Preview' found:  Xcode couldn't find a profile matching 'XC Ad Hoc: com.laundrapp.Preview'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

When I run the command bellow on it's own, I have no issue getting it to archive:

xcodebuild "-workspace" "/Users/andrefonseca/Documents/Customer App/Laundrapp.xcworkspace" "-scheme" "Laundrapp Staging" "clean" "archive" 

I copied this command from the prints from the codesigndoc when I run it.

**Comment by viktorbenei** [comment] 2016-11-02 05:57
Can you please include the whole log?

The (`xcodebuild ... archive`) command you see in the log is exactly what's executed by `codesigndoc`.

Also, as a general advise, please try to create an IPA from Xcode first and run codesigndoc only after that. Xcode sometimes generates code signing files on the fly, in the background, during the "export" (from Organizer). In that case the code signing files are only available after you do an export from Xcode.app, and `codesigndoc` can only collect files which are available on your Mac.

**Comment by viktorbenei** [comment] 2016-11-22 13:50
Closing this ticket because of not enough issue to reproduction the problem - @sketchydroide if you answer my previous question I'll reopen this ticket!

**Closed by viktorbenei** 2016-11-22 13:50 UTC
Labels: question
